[wokwi]
version = 1
firmware = './servidorweb.bin'
elf = './servidorweb.elf'

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8182"
to = "target:8000"
