[wokwi]
version = 1
firmware = './esp32-http-server.bin'
elf = './esp32-http-server.elf'

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"
visibility = "public"
